[default]
APP_NAME = "app_name"
DATABASE = "sqlite"
DEBUG = true
SECRET_KEY = "***"
DATABASE_URL = "sqlite:///db.sqlite"

[development]
APP_NAME = "project"
DATABASE = "postgresql"
DEBUG = true
SECRET_KEY = "***"
POSTGRES_USER = "user"
POSTGRES_PASSWORD = "***"
POSTGRES_HOST = "['127.0.0.1', 'localhost']"
POSTGRES_DB = "db"

[testing]
APP_NAME = "project"
DATABASE = "sqlite"
DEBUG = true
SECRET_KEY = "***"
DATABASE_URL = "sqlite:///db"

[production]
APP_NAME = "project"
DATABASE = "postgresql"
DEBUG = false
SECRET_KEY = "***"
POSTGRES_USER = "user"
POSTGRES_PASSWORD = "***"
POSTGRES_HOST = "['127.0.0.1', 'localhost']"
POSTGRES_DB = "db"