[default]
SECRET_KEY = "548JM6@aK!pO|DN:US,xUG6zF52yZXP"
MERCADOPAGO_PUBLIC_KEY = "TEST-b50118f2-6875-4eab-b1f2-55df2a01fef5"
MERCADOPAGO_ACCESS_TOKEN = "TEST-3070206317287648-031707-c6e11b557ecde6fb47409431b9b52278-221150409"


[staging]
SQLALCHEMY_DATABASE_URI = "postgresql://postgres.pnetnjaftmfzgumhgvit:Hampersoujr24@aws-0-sa-east-1.pooler.supabase.com:5432/postgres"
REDIS_URL = "rediss://red-cus5n0an91rc73di3440:NCMGqJ6UjrX2Xmf1FwQTFU2kmv75q7Xa@oregon-keyvalue.render.com:6379"


[production]
SQLALCHEMY_DATABASE_URI = "postgresql://postgres.yajhpyrjyrmhajktpqfr:Hampersoujr24@aws-0-sa-east-1.pooler.supabase.com:5432/postgres"
REDIS_URL = "redis://red-cutkipqj1k6c738dbpm0:6379"
