[default]
APP_NAME = "project"
DATABASE = "sqlite"
DEBUG = true
SECRET_KEY = "548JM6@aK!pO|DN:US,xUG6zF52yZXP"
DATABASE_URL = "sqlite:///db_default.sqlite"

[development]
APP_NAME = "project"
DATABASE = "sqlite"
DEBUG = true
SECRET_KEY = "%7:R~b!od`^5o6D|8MJ1T?V9yXD+^<#4Y!s+X1Gl,6>.e-N8Nmbe55brOShSaYV"
DATABASE_URL = "sqlite:///db_development.sqlite"

[testing]
APP_NAME = "project"
DATABASE = "sqlite"
DEBUG = true
SECRET_KEY = "xhq?WowZIP'9uRhxi<K&_=sR:X:<|%p"
DATABASE_URL = "sqlite:///db_testing.sqlite"

[production]
APP_NAME = "project"
DATABASE = "postgresql"
DEBUG = false
SECRET_KEY = "6oE5A30NThie4adyWfwUk3il?y<!++21:wdCdAgX:fMZQ>.adM_OJVTh&SsMg^?Q"
POSTGRES_USER = "db_user_production"
POSTGRES_PASSWORD = "db_password_production"
POSTGRES_HOST = "['127.0.0.1', 'localhost']"
POSTGRES_DB = "db_name_production"
