[default]
APP_NAME = "project"
DATABASE = "sqlite"
SECRET_KEY = "548JM6@aK!pO|DN:US,xUG6zF52yZXP"
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "project.ext.restapi:init_app",
    "project.ext.database:init_app"
]

[development]
FLASK_ENV = "development"
INCLUDES = ["default"]
TEMPLATES_AUTO_RELOAD = true
DEBUG = true
SQLALCHEMY_DATABASE_URI = "postgresql://myuser:mypassword1@localhost:5432/mydatabase"

[testing]
FLASK_ENV = "testing"
INCLUDES = ["default"]
SQLALCHEMY_DATABASE_URI = "sqlite:///db.testing.sqlite"
DEBUG = true

[production]
FLASK_ENV = "production"
INCLUDES = ["default"]
SQLALCHEMY_DATABASE_URI = "postgresql://hamper:H9hx4jWB5SErLZ3jGkagsAcj6AZRpto0@dpg-cookos8l5elc738j9tjg-a.oregon-postgres.render.com/hamper"

[homologacao]
FLASK_ENV = "homologacao"
INCLUDES = ["default"]
SQLALCHEMY_DATABASE_URI = "postgresql://hamper:H9hx4jWB5SErLZ3jGkagsAcj6AZRpto0@dpg-cookos8l5elc738j9tjg-a.oregon-postgres.render.com/hamper"
