[default]
APP_NAME = "project"
DATABASE = "sqlite"
ERROR_404_HELP = false
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = ["project.ext.restapi:init_app", "project.ext.database:init_app"]

[testing]
FLASK_ENV = "local"
INCLUDES = ["default"]
TEMPLATES_AUTO_RELOAD = true
DEBUG = true
SQLALCHEMY_DATABASE_URI = "sqlite:///test.db:memory:"
REDIS_URL = "redis://"

[local]
FLASK_ENV = "local"
INCLUDES = ["default"]
TEMPLATES_AUTO_RELOAD = true
DEBUG = true
SQLALCHEMY_DATABASE_URI = "postgresql://myuser:mypassword1@localhost:5432/mydatabase"
REDIS_URL = "redis://localhost:6379"
NOTIFICATION_URL = ''

[testing]
FLASK_ENV = "testing"
INCLUDES = ["default"]
TEMPLATES_AUTO_RELOAD = true
DEBUG = true
SQLALCHEMY_DATABASE_URI = "sqlite:///:memory:"
REDIS_URL = "redis://localhost:6379"
NOTIFICATION_URL = ''

[testing]
FLASK_ENV = "testing"
INCLUDES = ["default"]
TEMPLATES_AUTO_RELOAD = true
DEBUG = true
SQLALCHEMY_DATABASE_URI = "sqlite:///:memory:"
REDIS_URL = "redis://localhost:6379"

[staging]
FLASK_ENV = "staging"
INCLUDES = ["default"]
NOTIFICATION_URL = 'https://staging-hamper-backend.onrender.com/api/v1/notification'

[production]
FLASK_ENV = "production"
INCLUDES = ["default"]
NOTIFICATION_URL = ''
