"""fix database func now on sqlite

Revision ID: 6ad36fe0016a
Revises: ee3a3a94c577
Create Date: 2025-03-16 16:24:33.544955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad36fe0016a'
down_revision = 'ee3a3a94c577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=False)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('classification',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('classification',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
