"""add mercado pago transaction info to payment table

Revision ID: 98bb4b23640b
Revises: 8474eab0817f
Create Date: 2025-03-16 19:03:52.736393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bb4b23640b'
down_revision = '8474eab0817f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('qr_code_base64', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ticket_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mercadopago_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date_of_expiration', sa.DateTime(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=False)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('classification',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('classification',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('date_of_expiration')
        batch_op.drop_column('mercadopago_id')
        batch_op.drop_column('ticket_url')
        batch_op.drop_column('qr_code_base64')
        batch_op.drop_column('qr_code')

    # ### end Alembic commands ###
