"""empty message

Revision ID: dbd49da0c706
Revises: 9255441d2a22
Create Date: 2025-03-31 16:29:09.273131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd49da0c706'
down_revision = '9255441d2a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('establishment', schema=None) as batch_op:
        batch_op.alter_column('official_name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=45),
               existing_nullable=False)
        batch_op.alter_column('fantasy_name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=45),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['telephone'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('mercadopago_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('mercadopago_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('establishment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('fantasy_name',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
        batch_op.alter_column('official_name',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
