"""add client email

Revision ID: ee3a3a94c577
Revises: 5f156fd29ab8
Create Date: 2025-03-16 15:44:37.077826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3a3a94c577'
down_revision = '5f156fd29ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('cellphone', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('cpf', sa.String(length=11), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('address_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('address_complement', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('address_neighborhood', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=8), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_index(batch_op.f('ix_client_email'), ['email'], unique=False)
        batch_op.drop_column('client_address_number')
        batch_op.drop_column('client_address')
        batch_op.drop_column('client_address_complement')
        batch_op.drop_column('client_cpf')
        batch_op.drop_column('client_name')
        batch_op.drop_column('client_zip_code')
        batch_op.drop_column('client_address_neighborhood')
        batch_op.drop_column('client_cellphone')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=6),
               existing_nullable=False)

    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('classification',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('classification',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Float(precision=6),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_cellphone', sa.VARCHAR(length=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('client_address_neighborhood', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('client_zip_code', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('client_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('client_cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('client_address_complement', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('client_address', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('client_address_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_client_email'))
        batch_op.drop_column('email')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('address_neighborhood')
        batch_op.drop_column('address_complement')
        batch_op.drop_column('address_number')
        batch_op.drop_column('address')
        batch_op.drop_column('cpf')
        batch_op.drop_column('cellphone')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
