"""initial migration

Revision ID: fff14b8641de
Revises:
Create Date: 2025-03-16 22:57:42.653676

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fff14b8641de"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("cellphone", sa.String(length=11), nullable=False),
        sa.Column("cpf", sa.String(length=11), nullable=False),
        sa.Column("address", sa.String(length=120), nullable=False),
        sa.Column("address_number", sa.Integer(), nullable=False),
        sa.Column("address_complement", sa.String(length=120), nullable=False),
        sa.Column("address_neighborhood", sa.String(length=40), nullable=True),
        sa.Column("zip_code", sa.String(length=8), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_client_email"), ["email"], unique=False)

    op.create_table(
        "restaurant",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("description", sa.String(length=120), nullable=False),
        sa.Column("classification", sa.Float(precision=3), nullable=False),
        sa.Column("location", sa.String(length=120), nullable=False),
        sa.Column("url_image_logo", sa.String(length=800), nullable=True),
        sa.Column("url_image_banner", sa.String(length=800), nullable=True),
        sa.Column("telephone", sa.String(length=11), nullable=False),
        sa.Column("has_plastic", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("firstname", sa.String(length=20), nullable=False),
        sa.Column("lastname", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("restaurant_id", sa.Integer(), nullable=True),
        sa.Column("total_value", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pre_order",
                "confirmed",
                "doing",
                "done",
                "canceled",
                name="order_status",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("value", sa.Float(precision=3), nullable=False),
        sa.Column("description", sa.String(length=120), nullable=False),
        sa.Column("url_image", sa.String(length=800), nullable=True),
        sa.Column(
            "food_type",
            sa.Enum(
                "Italiana",
                "Japonesa",
                "Árabe",
                "Chinesa",
                "Brasileira",
                "Mexicana",
                "Lanches",
                "Pizza",
                "Doces",
                name="food_type",
            ),
            nullable=False,
        ),
        sa.Column("has_gluten", sa.Boolean(), nullable=False),
        sa.Column("has_lactose", sa.Boolean(), nullable=False),
        sa.Column("is_vegan", sa.Boolean(), nullable=False),
        sa.Column("is_vegetarian", sa.Boolean(), nullable=False),
        sa.Column("restaurant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_product_association",
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
    )
    op.create_table(
        "payment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("total_value", sa.Float(), nullable=True),
        sa.Column(
            "type", sa.Enum("Dinheiro", "Pix", name="payment_type"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "authorized",
                "in_process",
                "in_mediation",
                "rejected",
                "cancelled",
                "refunded",
                "charged_back",
                name="payment_status",
            ),
            nullable=True,
        ),
        sa.Column("qr_code", sa.String(), nullable=True),
        sa.Column("qr_code_base64", sa.Text(), nullable=True),
        sa.Column("ticket_url", sa.String(), nullable=True),
        sa.Column("mercadopago_id", sa.String(), nullable=True),
        sa.Column("date_of_expiration", sa.DateTime(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "products_restaurants",
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("restaurant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurant.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products_restaurants")
    op.drop_table("payment")
    op.drop_table("order_product_association")
    op.drop_table("product")
    op.drop_table("order")
    op.drop_table("user")
    op.drop_table("restaurant")
    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_client_email"))

    op.drop_table("client")
    # ### end Alembic commands ###
